name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/baez90/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src/tand/
    - name: Pack for deploying package
      run: dotnet pack --configuration Release
      working-directory: ./src/tand/
    - name: Publish Core package
      run: dotnet nuget push "Tand.Core/bin/Release/Tand.Core.0.0.1.nupkg"
      working-directory: ./src/tand/
    - name: Publish DI extensions package
      run: dotnet nuget push "Tand.Extensions.DependencyInjection/bin/Release/Tand.Extensions.DependencyInjection.0.0.1.nupkg"
      working-directory: ./src/tand/    
